#pragma once

#include <Vulkan/Config.hpp>

#define JKR_NO_STAGING_BUFFERS
#define JKR_USE_VERTEX_BUFFER_TO_STORE_FONT_TEXTURE_INDICES

#ifdef USE_VARIABLE_DESCRIPTOR_INDEXING_FEATURE
//      #define JKR_USE_VARIABLE_DES_INDEXING
#endif

